### ISSUE TITLE
needs "parseInt" function to work

### ISSUE THREAD

**Issue by zachy9** [jiridj/hugo-collapsible-code#1]
Hi thanks for the shortcode — it wasn't working for me and I finally figured out that in the "makeCollapsible" function, this line:

`    if (div.offsetHeight > height {`

Needs to be changed to:

`    if (div.offsetHeight > parseInt(height, 10)) {`

Because the maxHeight (max-height in CSS) property is not a number, it's a string with a 'px' at the end.

Likewise the var height at the top needs to be set to '300px' rather than just 300. Is this something that changed in the last few years since you made this? Possibly. Thanks!

**Comment by jiridj** [comment]
Thanks! I haven't looked at this particular piece of code for a long time. I'll make the update.

**Comment by jiridj** [comment]
updated.
