### ISSUE TITLE
Question on shortcode options

### ISSUE THREAD

**Issue by mrodriguez3313** [jiridj/hugo-collapsible-code#4]
Hi I am confused about what shortcode options are available to me. I ask because in [code.html](https://github.com/jiridj/hugo-collapsible-code/blob/master/layouts/shortcodes/code.html) it shows that it can accept two different arguments.

Secondly, what syntax highlighting options are available for the shortcode?

Thirdly, and slightly unrelated, I would suggest a faq for the readme so I newbs at frontend (like me) can try to debug common problems. (For example, it took me a while to realize I had to reference the stylesheet and the script somewhere in my project's Hugo framework)

Great project btw. I got it to work. Will probably find more places to use it :thumbsup:

**Comment by jiridj** [comment]
Thanks Marco! I'm glad you got it to work. 
I've added a few usage tips to the README.
